apiVersion: v1
kind: Service
metadata:
  name: scout-api
  labels:
    app.kubernetes.io/name: scout-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scout-api
  ports:
    - name: http
      port: 3001
      targetPort: http
